/**:
  ros__parameters:
    # Planner Parameters
    heading_weight: 0.1
    min_record_distance: 0.1
    enable_object_collision_estimator: True
    goal_distance_threshold_m: 0.75
    goal_angle_threshold_rad: 1.57
    loop_trajectory: False
    loop_max_gap_m: 0.6 # Twice car-length
    skip_first_velocity: False
    # ROS Parameters
    vehicle_state: '/autodrive/nigel_1/odom' # /particle_filter/pose/odom
    planned_trajectory: '/planning/trajectory'