/**:
  ros__parameters:
    # marker_size
    marker_size: 0.6

    # target_tag_ids
    target_tag_ids: ['0','4','5']

    # covariance
    covariance: [0.1, 0.0, 0.0,   0.0,  0.0, 0.0,
                 0.0, 0.1, 0.0,   0.0,  0.0, 0.0,
                 0.0, 0.0, 0.1,   0.0,  0.0, 0.0,
                 0.0, 0.0, 0.0, 0.001,  0.0, 0.0,
                 0.0, 0.0, 0.0,   0.0, 0.01, 0.0,
                 0.0, 0.0, 0.0,   0.0,  0.0, 0.01]

    # Detect AR-Tags within this range and publish the pose of ego vehicle
    range: 6.0  # [m]

    # Camera frame id
    camera_frame: "camera"
