/**:
  ros__parameters:
    # When the processing time exceeds the max_allowed_processing_time,
    # a warning will be triggered.
    max_allowed_processing_time: 200.0 # in milliseconds
    # If the warning is triggered more than max_consecutive_warn_count times in a row,
    # an error diagnostic message will be sent.
    max_consecutive_warn_count: 10
