/**:
  # general parameters shared by all vesc-related nodes
  ros__parameters:
    # erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
    speed_to_erpm_gain: 7400.0 # If the odometry estimate is larger than the actual distance traveled increase the gain, else decrease
    speed_to_erpm_offset: 0.0 # This term will constantly correct odometry drift (change ONLY for a "drifting" VESC)

    # servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
    steering_angle_to_servo_gain: -1.2135 # This term defines the steering limit (tune for smallest absolute value which achieves steer limit) and axis convention (e.g. set -ve gain for CCW/left-turn +ve convention)
    steering_angle_to_servo_offset: 0.5619 # This term defines zero-steer offset (tune for near-perfect straight line motion)

    port: /dev/sensors/vesc
    duty_cycle_min: 0.0
    duty_cycle_max: 0.8
    current_min: 0.0
    current_max: 100.0
    brake_min: -20000.0
    brake_max: 200000.0
    speed_min: -60000.0
    speed_max: 60000.0
    position_min: 0.0
    position_max: 0.0
    servo_min: 0.15
    servo_max: 0.85

# No longer needed, all parameters are shared
# ackermann_to_vesc_node:
#   ros__parameters:

vesc_to_odom_node:
  ros__parameters:
    odom_frame: odom
    base_frame: base_link
    # publish odom to base link tf
    publish_tf: true
    use_servo_cmd_to_calc_angular_velocity: true
    # car wheelbase is 0.324 m
    wheelbase: 0.324

# No longer needed, all parameters are shared
# vesc_driver:
#   ros__parameters:

throttle_interpolator:
  ros__parameters:
    rpm_input_topic: commands/motor/unsmoothed_speed
    rpm_output_topic: commands/motor/speed
    servo_input_topic: commands/servo/unsmoothed_position
    servo_output_topic: commands/servo/position

    # servo smoother - limits acceleration and smooths anything above limit
    max_acceleration: 2.5 # meters/second^2
    throttle_smoother_rate: 75.0 # messages/sec
    # servo smoother - limits rotation speed and smooths anything above limit
    max_servo_speed: 3.2 # radians/second
    servo_smoother_rate: 75.0 # messages/sec