files:
  - { package: system_diagnostic_monitor, path: config/map.yaml }
  - { package: system_diagnostic_monitor, path: config/localization.yaml }
  - { package: system_diagnostic_monitor, path: config/planning.yaml }
  - { package: system_diagnostic_monitor, path: config/perception.yaml }
  - { package: system_diagnostic_monitor, path: config/control.yaml }
  - { package: system_diagnostic_monitor, path: config/vehicle.yaml }
  - { package: system_diagnostic_monitor, path: config/system.yaml }

links:
  - path: /autoware
    type: and
    list:
      - { type: link, path: /autoware/operation/stop }
      - { type: link, path: /autoware/operation/autonomous }
      - { type: link, path: /autoware/operation/local }
      - { type: link, path: /autoware/operation/remote }
      - { type: link, path: /autoware/operation/emergency-stop }
      - { type: link, path: /autoware/operation/comfortable-stop }
      - { type: link, path: /autoware/operation/pull-over }

  - path: /autoware/operation/stop
    type: debug-ok

  - path: /autoware/operation/autonomous
    type: and
    list:
      - { type: link, path: /autoware/map }
      - { type: link, path: /autoware/localization }
      - { type: link, path: /autoware/planning }
      - { type: link, path: /autoware/perception }
      - { type: link, path: /autoware/control }
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/operation/local
    type: and
    list:
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/operation/remote
    type: and
    list:
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/operation/emergency-stop
    type: and
    list:
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/operation/comfortable-stop
    type: and
    list:
      - { type: link, path: /autoware/map }
      - { type: link, path: /autoware/localization }
      - { type: link, path: /autoware/planning }
      - { type: link, path: /autoware/perception }
      - { type: link, path: /autoware/control }
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }

  - path: /autoware/operation/pull-over
    type: and
    list:
      - { type: link, path: /autoware/map }
      - { type: link, path: /autoware/localization }
      - { type: link, path: /autoware/planning }
      - { type: link, path: /autoware/perception }
      - { type: link, path: /autoware/control }
      - { type: link, path: /autoware/vehicle }
      - { type: link, path: /autoware/system }
