nodes:
  - path: /autoware/control
    type: and
    list:
      - { type: link, link: /autoware/control/topic_rate_check/trajectory_follower }
      - { type: link, link: /autoware/control/topic_rate_check/control_command }

  - path: /autoware/control/topic_rate_check/trajectory_follower
    diag: "topic_state_monitor_trajectory_follower_control_cmd: control_topic_status"

  - path: /autoware/control/topic_rate_check/control_command
    diag: "topic_state_monitor_control_command_control_cmd: control_topic_status"
