units:
  - path: /autoware/planning
    type: short-circuit-and
    list:
      - { type: link, path: /autoware/planning/routing/state }
      - type: and
        list:
          - { type: link, path: /autoware/planning/routing/topic_rate_check/route }
          - { type: link, path: /autoware/planning/routing/topic_rate_check/trajectory }

diags:
  - path: /autoware/planning/routing/state
    name: "component_state_diagnostics: route_state"

  - path: /autoware/planning/topic_rate_check/route
    name: "topic_state_monitor_mission_planning_route: planning_topic_status"
    hardware: topic_state_monitor

  - path: /autoware/planning/topic_rate_check/trajectory
    name: "topic_state_monitor_scenario_planning_trajectory: planning_topic_status"
    hardware: topic_state_monitor
