/**:
  ros__parameters:
    traffic_light:
      stop_margin: 0.0
      tl_state_timeout: 1.0
      stop_time_hysteresis: 0.1
      yellow_lamp_period: 2.75
      enable_pass_judge: true
      enable_rtc: true # If set to true, the scene modules require approval from the rtc (request to cooperate) function. If set to false, the modules can be executed without requiring rtc approval

      v2i:
        use_rest_time: true
        last_time_allowed_to_pass: 2.0 # relative time against at the time of turn to red
        velocity_threshold: 0.5 # change the decision logic whether the current velocity is faster or not
        required_time_to_departure: 3.0 # prevent low speed pass
