/adapi/node/autoware_state:
  ros__parameters:
    update_rate: 10.0

/adapi/node/motion:
  ros__parameters:
    require_accept_start: false
    stop_check_duration: 1.0

/adapi/node/routing:
  ros__parameters:
    stop_check_duration: 1.0

/adapi/node/vehicle_door:
  ros__parameters:
    check_autoware_control: true
