# see AvoidanceParameters description in avoidance_module.hpp for description.
/**:
  ros__parameters:
    avoidance:
      threshold_distance_object_is_on_center: 0.0 # [m]
      threshold_speed_object_is_stopped: 1.0      # [m/s]
      object_check_forward_distance: 150.0        # [m]
      object_check_backward_distance: 2.0         # [m]
      lateral_collision_margin: 2.0               # [m]
      longitudinal_collision_margin: 3.0          # [m]
      time_to_start_avoidance: 1.0                # [s]
      min_distance_to_start_avoidance: 1.0        # [m]
      time_avoiding: 7.0                          # [s]
      min_distance_avoiding: 50.0                 # [m]

      min_distance_avoidance_end_to_object: 5.0   # [m]
      time_avoidance_end_to_object: 1.0           # [s]

      nominal_lateral_jerk: 0.3   # [m/s3]
      max_lateral_jerk: 2.0       # [m/s3]
