/**:
  ros__parameters:
    verbose: false

    planning_hz: 10.0
    backward_path_length: 5.0
    forward_path_length: 300.0
    backward_length_buffer_for_end_of_pull_over: 5.0
    backward_length_buffer_for_end_of_pull_out: 5.0
    minimum_pull_over_length: 16.0

    refine_goal_search_radius_range: 7.5

    # parameters for turn signal decider
    turn_signal_intersection_search_distance: 30.0
    turn_signal_intersection_angle_threshold_deg: 15.0
    turn_signal_minimum_search_distance: 10.0
    turn_signal_search_time: 3.0
    turn_signal_shift_length_threshold: 0.3
    turn_signal_on_swerving: true

    enable_akima_spline_first: false
    input_path_interval: 2.0
    output_path_interval: 2.0

    visualize_maximum_drivable_area: true

    lateral_distance_max_threshold: 2.0
    longitudinal_distance_min_threshold: 3.0

    expected_front_deceleration: -1.0
    expected_rear_deceleration: -1.0

    expected_front_deceleration_for_abort: -1.0
    expected_rear_deceleration_for_abort: -2.0

    rear_vehicle_reaction_time: 2.0
    rear_vehicle_safety_time_margin: 1.0

    # USE ONLY WHEN THE OPTION COMPILE_WITH_OLD_ARCHITECTURE IS SET TO FALSE.
    # https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/CMakeLists.txt
    # NOTE: The smaller the priority number is, the higher the module priority is.
    ext_request_lane_change_left:
      enable_module: false
      enable_simultaneous_execution: false
      priority: 6
      max_module_size: 1

    ext_request_lane_change_right:
      enable_module: false
      enable_simultaneous_execution: false
      priority: 6
      max_module_size: 1

    lane_change_left:
      enable_module: true
      enable_simultaneous_execution: true
      priority: 5
      max_module_size: 1

    lane_change_right:
      enable_module: true
      enable_simultaneous_execution: false
      priority: 4
      max_module_size: 1

    pull_out:
      enable_module: true
      enable_simultaneous_execution: false
      priority: 0
      max_module_size: 1

    side_shift:
      enable_module: true
      enable_simultaneous_execution: false
      priority: 2
      max_module_size: 1

    pull_over:
      enable_module: true
      enable_simultaneous_execution: false
      priority: 1
      max_module_size: 1

    avoidance:
      enable_module: true
      enable_simultaneous_execution: false
      priority: 3
      max_module_size: 1
