/**:
    ros__parameters:
      data_params:
        N: 6  # camera num
        H: 900 # image height
        W: 1600 # image width
        cams: ["CAM_FRONT_LEFT", "CAM_FRONT", "CAM_FRONT_RIGHT", "CAM_BACK_LEFT", "CAM_BACK", "CAM_BACK_RIGHT"]
      post_process_params:
        # post-process params
        score_threshold: 0.2
        class_names: ["car", "truck", "construction_vehicle", "bus", "trailer", "barrier", "motorcycle", "bicycle", "pedestrian", "traffic_cone"]
