/**:
  ros__parameters:
    input_twist_topic_type: "twist"
    output_frame: ""
    keep_input_frame_in_synchronized_pointcloud: false
    input_topics: []
    synchronized_pointcloud_postfix: "pointcloud"
    max_queue_size: 5
    timeout_sec: 0.1
    input_offset: []
    