/**:
  ros__parameters:
    # constraints param for normal driving
    normal:
      min_acc: -0.5         # min deceleration [m/ss]
      max_acc: 0.5          # max acceleration [m/ss]
      min_jerk: -0.4        # min jerk [m/sss]
      max_jerk: 0.4         # max jerk [m/sss]

    # constraints to be observed
    limit:
      min_acc: -0.9         # min deceleration limit [m/ss]
      max_acc: 0.9          # max acceleration limit [m/ss]
      min_jerk: -0.6        # min jerk limit [m/sss]
      max_jerk: 0.6         # max jerk limit [m/sss]
