/**:
  ros__parameters:
    use_predicted_path: true
    use_generated_path: true
    use_imu_data_: true
    voxel_grid_x_: 0.05
    voxel_grid_y_: 0.05
    voxel_grid_z_: 100000.0
    min_generated_path_length: 0.5
    expand_width: 0.1
    longitudinal_offset: 1.5
    t_response: 1.0
    a_ego_min: -3.0
    a_obj_min: -1.0
    prediction_time_horizon: 2.0
    prediction_time_interval: 0.1
