/**:
  ros__parameters:
    use_imu_data_: false
    voxel_grid_x_: 0.05
    voxel_grid_y_: 0.05
    voxel_grid_z_: 100000.0
    lateral_offset: 1.0
    longitudinal_offset: 1.5
    t_response: 1.0
    a_ego_min: -3.0
    a_obj_min: -1.0
    prediction_time_horizon: 2.0
    prediction_time_interval: 0.1
