---
- hosts: localhost
  connection: local
  become: no
  vars_prompt:
    - name: yn_gpu
      prompt: "Do you install GPU modules(cuda: 11.1, cudnn: 8.0.5, TensorRT: 7.2.1)? (y/n)"
      default: "y"
      private: no
  pre_tasks:
    - pause:
        seconds: 10
        prompt: "[Warning]: Skip install GPU modules. Try manually installing these modules to execute nodes depending on TensorRT."
      when: yn_gpu != 'y'
  roles:
    - { role: cuda, when: yn_gpu == 'y' }
    - { role: tensorrt, when: yn_gpu == 'y' }
    - { role: ros2, rosdistro: foxy }
    - { role: autoware, rosdistro: foxy }
    - { role: kvaser }  # Temporary for ros2 porting
    # - { role: pacmod, rosdistro: foxy }  # Temporary for ros2 porting
    # - { role: ros, release: melodic }
