/**:
  ros__parameters:
    class_names: ["CAR", "TRUCK", "BUS", "BICYCLE", "PEDESTRIAN"]
    point_feature_size: 9  # x, y, z, time-lag and car, pedestrian, bicycle
    max_voxel_size: 40000
    point_cloud_range: [-102.4, -102.4, -4.0, 102.4, 102.4, 6.0]
    voxel_size: [0.32, 0.32, 10.0]
    downsample_factor: 1
    encoder_in_feature_size: 14
    yaw_norm_thresholds: [0.3, 0.0, 0.3]