/**:
  ros__parameters:
    planning_hz: 10.0
    backward_path_length: 5.0
    forward_path_length: 300.0
    waypoint_group_separation_threshold: 1.0
    lateral_distance_factor: 10.0

    enable_akima_spline_first: false
    input_path_interval: 2.0
