particle_filter:
  ros__parameters:
    # topic names
    scan_topic: '/scan'
    odometry_topic: 'ego_racecar/odom'
    # range data downsampling
    angle_step: 18
    max_particles: 1500
    squash_factor: 2.2
    # visualization
    viz: 1
    max_viz_particles: 60
    # ray marching method
    range_method: 'rmgpu'
    theta_discretization: 112
    # range data filtering
    max_range: 10
    fine_timing: 0
    publish_odom: 1
    # sensor model constants
    z_short: 0.01
    z_max: 0.07
    z_rand: 0.12
    z_hit: 0.75
    sigma_hit: 8.0
    # motion model dispersion constants
    motion_dispersion_x: 0.05
    motion_dispersion_y: 0.025
    motion_dispersion_theta: 0.25
    # sensor model variant, variant 2 good for rmgpu, 3 doesn't work for rmgpu
    rangelib_variant: 2

map_server:
  ros__parameters:
    # assuming map file is in particle_filter/maps
    map: 'pennovation'
