# Description:
#   name: diag name
#   sf_at: diag level where it becomes Safe Fault
#   lf_at: diag level where it becomes Latent Fault
#   spf_at: diag level where it becomes Single Point Fault
#
# Note:
# empty-value for sf_at, lf_at and spf_at is "none"
# default values are:
#   sf_at: "none"
#   lf_at: "warn"
#   spf_at: "error"
---
/**:
  ros__parameters:
    required_modules:
      autonomous_driving:
        names: [
            "/autoware/control/autonomous_driving/node_alive_monitoring",
            "/autoware/control/autonomous_driving/performance_monitoring/lane_departure",
            "/autoware/control/control_command_gate/node_alive_monitoring",

            "/autoware/localization/node_alive_monitoring",
            # "/autoware/localization/performance_monitoring/matching_score",
            # "/autoware/localization/performance_monitoring/localization_accuracy",

            "/autoware/map/node_alive_monitoring",

            "/autoware/perception/node_alive_monitoring",

            "/autoware/planning/node_alive_monitoring",
            "/autoware/planning/performance_monitoring/trajectory_validation",

            "/autoware/sensing/node_alive_monitoring",

            "/autoware/system/node_alive_monitoring",
            "/autoware/system/emergency_stop_operation",
            # "/autoware/system/resource_monitoring",

            "/autoware/vehicle/node_alive_monitoring",
          ]
        diag_level:
          /autoware/localization/performance_monitoring/matching_score: { sf_at: "warn", lf_at: "none", spf_at: "none" }
          /autoware/system/debug_data_logger: { sf_at: "warn", lf_at: "none", spf_at: "none" }
          /autoware/system/resource_monitoring: { sf_at: "warn", lf_at: "none", spf_at: "none" }

      external_control:
        names:
          [
            "/autoware/control/control_command_gate/node_alive_monitoring",
            "/autoware/control/external_control/external_command_selector/node_alive_monitoring",

            "/autoware/system/node_alive_monitoring",
            "/autoware/system/emergency_stop_operation",

            "/autoware/vehicle/node_alive_monitoring",
          ]
