name: build

on:
  schedule:
    - cron: "0 19 * * 0" # run at 4 AM JST on Sundays
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        branch:
          - tier4/universe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Install pip
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip

      - name: Install tools
        run: |
          sudo apt-get -y update
          sudo apt-get -y install curl git

      - name: Fix autoware.proj.repos for private repositories
        run: |
          sed -i -e "s|git@github.com:|https://github.com/|g" autoware.proj.repos

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadOf 'https://github.com'

      - name: Install vcstool
        run: |
          sudo apt-get -y update && sudo apt-get -y install curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get -y update && sudo apt-get -y install python3-vcstool

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.proj.repos

      - name: Run setup script
        run: |
          touch ~/.bashrc
          ./setup_ubuntu20.04.sh -c

      - name: Build
        run: |
          . /opt/ros/galactic/setup.sh
          colcon build \
            --event-handlers console_cohesion+ \
            --cmake-args -DCMAKE_BUILD_TYPE=Release
