name: build-test-tidy-pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  require-label:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/require-label.yaml@v1
    with:
      label: run:build-test-tidy-checks

  check-if-cuda-job-is-needed:
    needs: require-label
    runs-on: ubuntu-latest
    outputs:
      cuda_job_is_needed: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Check if relevant files changed
        id: check
        uses: tj-actions/changed-files@v45
        with:
          files: |
            perception/**
            sensing/**

      - name: Output result
        run: |
          echo "CUDA job needed: ${{ steps.check.outputs.any_changed }}"
        shell: bash

  build-and-test-differential:
    needs:
      - require-label
    uses: ./.github/workflows/build-and-test-differential.yaml
    with:
      container: ghcr.io/autowarefoundation/autoware:universe-devel
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  build-and-test-differential-cuda:
    needs: check-if-cuda-job-is-needed
    if: ${{ needs.check-if-cuda-job-is-needed.outputs.cuda_job_is_needed == 'true' }}
    uses: ./.github/workflows/build-and-test-differential.yaml
    with:
      container: ghcr.io/autowarefoundation/autoware:universe-devel
      container-suffix: -cuda
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  clang-tidy-differential:
    needs:
      - check-if-cuda-job-is-needed
      - build-and-test-differential
    if: ${{ needs.check-if-cuda-job-is-needed.outputs.cuda_job_is_needed == 'false' }}
    uses: ./.github/workflows/clang-tidy-differential.yaml
    with:
      container: ghcr.io/autowarefoundation/autoware:universe-devel

  clang-tidy-differential-cuda:
    needs:
      - build-and-test-differential-cuda
    uses: ./.github/workflows/clang-tidy-differential.yaml
    with:
      container: ghcr.io/autowarefoundation/autoware:universe-devel
      container-suffix: -cuda
