name: check-missing-packages

on:
  schedule:
    - cron: 0 19 * * 0 # run at 4 AM JST on Sundays
  workflow_dispatch:

jobs:
  check-missing-packages:
    runs-on: ubuntu-latest
    container: ros:${{ matrix.ros_distribution }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ros_distribution: galactic, package: __dummy__ }
    steps:
      - name: Check ros-${{ matrix.ros_distribution }}-${{ matrix.package }}
        id: check-package
        run: |
          sudo apt-get -y update
          result=$(apt-cache search ros-${{ matrix.ros_distribution }}-${{ matrix.package }})
          echo "::set-output name=result::$result"

      - name: Install ros-${{ matrix.ros_distribution }}-${{ matrix.package }}
        if: ${{ jobs.check-package.outputs.result != '' }}
        run: |
          sudo apt-get -y install ros-${{ matrix.ros_distribution }}-${{ matrix.package }}

      - name: Notify by raising an error
        if: ${{ jobs.check-package.outputs.result != '' }}
        run: |
          echo "ros-${{ matrix.ros_distribution }}-${{ matrix.package }} can be installed."
          exit 1
