name: dispatch-release-note
on:
  push:
    branches:
      - beta/v*
      - tier4/main
    tags:
      - v*
  workflow_dispatch:
    inputs:
      beta-branch-or-tag-name:
        description: The name of the beta branch or tag to write release note
        type: string
        required: true
jobs:
  dispatch-release-note:
    runs-on: ubuntu-latest
    name: release-repository-dispatch
    steps:
      - name: Set tag name
        id: set-tag-name
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            REF_NAME="${{ github.event.inputs.beta-branch-or-tag-name }}"
          else
            REF_NAME="${{ github.ref_name }}"
          fi
          echo ::set-output name=ref-name::"$REF_NAME"
          echo ::set-output name=tag-name::"${REF_NAME#beta/}"

      - name: Repository dispatch for release note
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/tier4/update-release-notes/dispatches" \
          -d '{"event_type":"${{ steps.set-tag-name.outputs.ref-name }}"}'
