name: Generate documentation

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "mkdocs.yml"
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.css"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "mkdocs.yml"
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.css"
  workflow_dispatch:

env:
  GITHUB_PAGES_URL: https://tier4.github.io/autoware.proj

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetch with depth=0 to calculate modified files
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install MkDocs
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install \
            fontawesome_markdown \
            markdown \
            mdx_truly_sane_lists \
            mdx_unimoji \
            mkdocs \
            mkdocs-exclude \
            mkdocs-material \
            mkdocs-same-dir \
            plantuml-markdown \
            pymdown-extensions \
            python-markdown-math

      - name: Build MkDocs
        run: |
          mkdocs build -f mkdocs.yml --verbose --clean

      - name: Move docs (push)
        if: ${{ !github.event.pull_request }}
        run: |
          mkdir -p public/tree
          mv site public/tree/${GITHUB_REF#refs/heads/}

      - name: Move docs (pull_request)
        if: ${{ github.event.pull_request }}
        run: |
          mkdir -p public/pulls
          mv site public/pulls/${{ github.event.pull_request.number }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true

      - name: Create comment body
        if: ${{ github.event.pull_request }}
        id: create_comment_body
        run: |
          base_url="${{ env.GITHUB_PAGES_URL }}/pulls/${{ github.event.pull_request.number }}/"
          ${GITHUB_WORKSPACE}/.github/create_doc_comment.sh "${base_url}" "origin/${{ github.event.pull_request.base.ref }}"

      - name: Find Comment
        if: ${{ github.event.pull_request }}
        id: find_comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Documentation

      - name: Comment PR
        if: ${{ github.event.pull_request }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.create_comment_body.outputs.comment_body }}
          edit-mode: replace
