name: Sync Fork

on:
  schedule:
    - cron: '33 16 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/autowarefoundation/autoware.universe
          upstream_branch: main
          downstream_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
