name: Sync Fork with Upstream

env:
  UPSTREAM_URL: "https://github.com/autowarefoundation/autoware.universe.git"
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        upstream_repo: https://github.com/autowarefoundation/autoware.universe.git
        upstream_branch: main
        downstream_branch: main
        token: ${{ secrets.GITHUB_TOKEN }}
