name: test release scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - "scripts/release/**"
  workflow_dispatch:

jobs:
  vcs-import-cache:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop

    steps:
      # https://github.com/osrf/docker_images/issues/535
      - name: Temporarily fix GPG problem
        run: |
          sudo rm /etc/apt/sources.list.d/ros2-latest.list

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache src
        id: cache-src
        uses: actions/cache@v2
        env:
          cache-name: cache-src
        with:
          path: ./src
          key: vcs-import-src

      - name: Fix autoware.proj.repos for private repositories
        if: steps.cache-src.outputs.cache-hit != 'true'
        run: |
          sed -i -e "s|git@github.com:|https://github.com/|g" autoware.proj.repos

      - name: Set git config for private repositories
        if: steps.cache-src.outputs.cache-hit != 'true'
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadof 'https://github.com'

      - name: Run vcs import
        if: steps.cache-src.outputs.cache-hit != 'true'
        run: |
          mkdir src
          vcs import src < autoware.proj.repos

  test-reference-release:
    needs: vcs-import-cache
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop

    steps:
      # https://github.com/osrf/docker_images/issues/535
      - name: Temporarily fix GPG problem
        run: |
          sudo rm /etc/apt/sources.list.d/ros2-latest.list

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          apt-get -y update
          apt-get -y install wget
          wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.1/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: Cache src
        id: cache-src
        uses: actions/cache@v2
        env:
          cache-name: cache-src
        with:
          path: ./src
          key: vcs-import-src

      - name: Fix autoware.proj.repos for private repositories
        run: |
          sed -i -e "s|git@github.com:|https://github.com/|g" autoware.proj.repos

      - name: Commit autoware.proj.repos to remove workspace diff
        run: |
          git add autoware.proj.repos
          git config --global user.email "actions@example.com"
          git config --global user.name "Github Actions"
          git commit -m "Update autoware.proj.repos in CI"

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadof 'https://github.com'

      - name: Create rc branches
        run: |
          ./scripts/release/create_reference_rc_branches.sh -y v0.0.0

      - name: Print versions
        run: |
          git branch
          cat autoware.proj.repos
          vcs custom src --git --args branch

      - name: Check result
        run: |
          git branch --show-current | grep "^rc/v0.0.0" || false
          cat autoware.proj.repos | grep autoware/autoware.iv -A3 | grep "version: rc/v0.0.0" || false
          cat autoware.proj.repos | grep autoware/launcher -A3 | grep "version: rc/v0.0.0" || false

      - name: Create release tags
        run: |
          ./scripts/release/create_reference_release_tags.sh -y v0.0.0

      - name: Print versions
        run: |
          git branch
          git describe --tags
          cat autoware.proj.repos
          vcs custom src --git --args branch

      - name: Check result
        run: |
          test "$(git branch --show-current)" = "" || false
          git describe --tags | grep "^v0.0.0" || false
          cat autoware.proj.repos | grep autoware/autoware.iv -A3 | grep "version: v0.0.0" || false
          cat autoware.proj.repos | grep autoware/launcher -A3 | grep "version: v0.0.0" || false

  test-product-release:
    needs: vcs-import-cache
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop

    steps:
      # https://github.com/osrf/docker_images/issues/535
      - name: Temporarily fix GPG problem
        run: |
          sudo rm /etc/apt/sources.list.d/ros2-latest.list

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          apt-get -y update
          apt-get -y install wget
          wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.1/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: Cache src
        id: cache-src
        uses: actions/cache@v2
        env:
          cache-name: cache-src
        with:
          path: ./src
          key: vcs-import-src

      - name: Fix autoware.proj.repos for private repositories
        run: |
          sed -i -e "s|git@github.com:|https://github.com/|g" autoware.proj.repos

      - name: Commit autoware.proj.repos to remove workspace diff
        run: |
          git add autoware.proj.repos
          git config --global user.email "actions@example.com"
          git config --global user.name "Github Actions"
          git commit -m "Update autoware.proj.repos in CI"

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadof 'https://github.com'

      - name: Create rc branches
        run: |
          ./scripts/release/create_product_rc_branches.sh -y --change-reference-repositories rc/v0.0.0 v0.0.1

      - name: Print versions
        run: |
          git branch
          cat autoware.proj.repos
          vcs custom src --git --args branch

      - name: Check result
        run: |
          git branch --show-current | grep "^rc/v0.0.1" || false
          cat autoware.proj.repos | grep autoware/autoware.iv -A3 | grep "version: rc/v0.0.0" || false
          cat autoware.proj.repos | grep autoware/launcher -A3 | grep "version: rc/v0.0.1" || false

      - name: Create release tags
        run: |
          ./scripts/release/create_product_release_tags.sh -y --change-reference-repositories v0.0.0 v0.0.1

      - name: Print versions
        run: |
          git branch
          git describe --tags
          cat autoware.proj.repos
          vcs custom src --git --args branch

      - name: Check result
        run: |
          test "$(git branch --show-current)" = "" || false
          git describe --tags | grep "^v0.0.1" || false
          cat autoware.proj.repos | grep autoware/autoware.iv -A3 | grep "version: v0.0.0" || false
          cat autoware.proj.repos | grep autoware/launcher -A3 | grep "version: v0.0.1" || false

  test-product-release-after-reference-release:
    needs: vcs-import-cache
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop

    steps:
      # https://github.com/osrf/docker_images/issues/535
      - name: Temporarily fix GPG problem
        run: |
          sudo rm /etc/apt/sources.list.d/ros2-latest.list

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          apt-get -y update
          apt-get -y install wget
          wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.1/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: Cache src
        id: cache-src
        uses: actions/cache@v2
        env:
          cache-name: cache-src
        with:
          path: ./src
          key: vcs-import-src

      - name: Fix autoware.proj.repos for private repositories
        run: |
          sed -i -e "s|git@github.com:|https://github.com/|g" autoware.proj.repos

      - name: Commit autoware.proj.repos to remove workspace diff
        run: |
          git add autoware.proj.repos
          git config --global user.email "actions@example.com"
          git config --global user.name "Github Actions"
          git commit -m "Update autoware.proj.repos in CI"

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadof 'https://github.com'

      - name: Prepare reference release
        run: |
          ./scripts/release/create_reference_rc_branches.sh -y v0.0.0
          ./scripts/release/create_reference_release_tags.sh -y v0.0.0

      - name: Create rc branches
        run: |
          ./scripts/release/create_product_rc_branches.sh -y v0.0.0 v0.0.1

      - name: Print versions
        run: |
          git branch
          cat autoware.proj.repos
          vcs custom src --git --args branch

      - name: Check result
        run: |
          git branch --show-current | grep "^rc/v0.0.1" || false
          cat autoware.proj.repos | grep autoware/autoware.iv -A3 | grep "version: v0.0.0" || false
          cat autoware.proj.repos | grep autoware/launcher -A3 | grep "version: rc/v0.0.1" || false

      - name: Create release tags
        run: |
          ./scripts/release/create_product_release_tags.sh -y v0.0.0 v0.0.1

      - name: Print versions
        run: |
          git branch
          git describe --tags
          cat autoware.proj.repos
          vcs custom src --git --args branch

      - name: Check result
        run: |
          test "$(git branch --show-current)" = "" || false
          git describe --tags | grep "^v0.0.1" || false
          cat autoware.proj.repos | grep autoware/autoware.iv -A3 | grep "version: v0.0.0" || false
          cat autoware.proj.repos | grep autoware/launcher -A3 | grep "version: v0.0.1" || false

  test-experiment-branch:
    needs: vcs-import-cache
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop

    steps:
      # https://github.com/osrf/docker_images/issues/535
      - name: Temporarily fix GPG problem
        run: |
          sudo rm /etc/apt/sources.list.d/ros2-latest.list

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          apt-get -y update
          apt-get -y install wget
          wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.1/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: Cache src
        id: cache-src
        uses: actions/cache@v2
        env:
          cache-name: cache-src
        with:
          path: ./src
          key: vcs-import-src

      - name: Fix autoware.proj.repos for private repositories
        run: |
          sed -i -e "s|git@github.com:|https://github.com/|g" autoware.proj.repos

      - name: Commit autoware.proj.repos to remove workspace diff
        run: |
          git add autoware.proj.repos
          git config --global user.email "actions@example.com"
          git config --global user.name "Github Actions"
          git commit -m "Update autoware.proj.repos in CI"

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadof 'https://github.com'

      - name: Create experiment branches
        run: |
          ./scripts/release/create_experiment_branches.sh -y 20210123-test

      - name: Print versions
        run: |
          git branch
          cat autoware.proj.repos
          vcs custom src --git --args branch

      - name: Check result
        run: |
          git branch --show-current | grep "^experiment/20210123-test" || false
          cat autoware.proj.repos | grep autoware/autoware.iv -A3 | grep "version: experiment/20210123-test" || false
          cat autoware.proj.repos | grep autoware/launcher -A3 | grep "version: experiment/20210123-test" || false
