name: update-beta-branch

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

env:
  SYNC_BRANCH_PREFIX: update-beta-branch

jobs:
  search-beta-branch:
    runs-on: ubuntu-latest
    outputs:
      beta-branch: ${{ steps.search-beta-branch.outputs.value }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Search beta branch
        id: search-beta-branch
        run: |
          branch_names=$(git branch -a | grep -E 'remotes/origin/beta/v[0-9]+(\.[0-9]+)*$' | sed -E 's|.*(beta/.*)|\1|g')
          if [ -n "$branch_names" ]; then
            branch_names_json=$(printf '"%s", ' $branch_names)
            branch_names_json="[${branch_names_json%, }]"
            echo ::set-output name=value::"$branch_names_json"
          fi
          echo "Detected beta branch: $branch_names_json"

  update-beta-branch:
    needs: search-beta-branch
    if: ${{ needs.search-beta-branch.outputs.beta-branch != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        beta-branch: ${{ fromJson(needs.search-beta-branch.outputs.beta-branch) }}
    steps:
      - name: Set BASE_BRANCH
        run: |
          echo "BASE_BRANCH=${{ matrix.beta-branch }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_BRANCH }}
          fetch-depth: 0

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Install vcstool
        run: |
          sudo apt update && sudo apt install curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update && sudo apt-get install python3-vcstool

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/.insteadOf 'https://github.com/'
          git config --global url.https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/.insteadOf 'git@github.com:'

      - name: Set git config
        run: |
          git config --local user.email "actions@example.com"
          git config --local user.name "Github Actions"

      - name: Run update script
        run: |
          git clone git@github.com:tier4/autoware-release-scripts.git
          ./autoware-release-scripts/scripts/update_beta_branches.sh
          rm -rf autoware-release-scripts/ src/

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore: update beta branch for ${{ env.BASE_BRANCH }}"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          signoff: false
          base: ${{ env.BASE_BRANCH }}
          branch: ${{ env.SYNC_BRANCH_PREFIX }}/${{ env.BASE_BRANCH }}
          delete-branch: true
          title: "chore: update beta branch for ${{ env.BASE_BRANCH }}"
          body: |
            update beta branch for ${{ env.BASE_BRANCH }}
          labels: |
            bot
            update-beta-branch
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"

      - name: Enable auto-merge
        if: ${{ steps.create-pr.outputs.pull-request-operation == 'created' }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
