name: update rc branch

on:
  schedule:
    - cron: "0 19 * * *" # run at 4 AM JST
  workflow_dispatch:

env:
  SYNC_BRANCH_PREFIX: update-rc-branch

jobs:
  update-rc-branch:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        rc_branch:
          - rc/v1.3.0

    steps:
      - name: Set BASE_BRANCH
        run: |
          echo "BASE_BRANCH=${{ matrix.rc_branch }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BASE_BRANCH }}
          fetch-depth: 0

      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Install vcstool
        run: |
          sudo apt update && sudo apt install curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update && sudo apt-get install python3-vcstool

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/.insteadOf 'https://github.com/'
          git config --global url.https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/.insteadOf 'git@github.com:'

      - name: Set git config
        run: |
          git config --local user.email "actions@example.com"
          git config --local user.name "Github Actions"

      - name: Run update script
        run: |
          git clone git@github.com:tier4/autoware-release-scripts.git
          ./autoware-release-scripts/scripts/update_rc_branches.sh
          rm -rf src

      - name: Create PR
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: update rc branch
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          signoff: false
          base: ${{ env.BASE_BRANCH }}
          branch: "${{ env.SYNC_BRANCH_PREFIX }}/${{ env.BASE_BRANCH }}"
          delete-branch: true
          title: update rc branch
          body: |
            update rc branch
          labels: |
            update-rc-branch
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.create_pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}"
