name: update-codeowners-from-packages

on:
  push:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  check-secret:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/check-secret.yaml@v1
    secrets:
      secret: ${{ secrets.APP_ID }}

  update-codeowners-from-packages:
    needs: check-secret
    if: ${{ needs.check-secret.outputs.set == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Run update-codeowners-from-packages
        uses: isamu-takagi/autoware-github-actions/update-codeowners-from-packages@feat/code-owners-advanced-settings
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pr-labels: |
            bot
            update-codeowners-from-packages
          # auto-merge-method: squash
